# Generated by Django 3.1 on 2020-09-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20200927_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='patron',
            field=models.CharField(default='static/imagenes/<django.db.models.fields.CharField>.jpeg', max_length=200),
        ),
    ]
