# Generated by Django 3.1 on 2020-09-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_producto_patron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='patron',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='scriptMP',
        ),
        migrations.AddField(
            model_name='producto',
            name='scriptMPL',
            field=models.TextField(default="<div class='btn btn-danger' style='margin: 0.5rem;'>Error</div>"),
        ),
        migrations.AddField(
            model_name='producto',
            name='scriptMPS',
            field=models.TextField(default="<div class='btn btn-danger' style='margin: 0.5rem;'>Error</div>"),
        ),
    ]
