# Generated by Django 3.1 on 2020-09-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20200927_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='scriptMPL',
            field=models.TextField(default="<div class='btn btn-danger'>Error</div>"),
        ),
        migrations.AlterField(
            model_name='producto',
            name='scriptMPS',
            field=models.TextField(default="<div class='btn btn-danger'>Error</div>"),
        ),
    ]
